package com.example.bmmoney;

import android.os.Bundle; import android.content.*; import android.text.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import com.example.bmmoney.data.*; import com.example.bmmoney.remote.FirebaseSyncManager; import com.google.android.material.button.MaterialButton;

public class AddTransactionActivity extends AppCompatActivity {
    private EditText edtTitle, edtAmount, edtNote; private Spinner spinnerCategory; private RadioButton radioIncome; private MaterialButton btnSave; private AppDatabase database; private SharedPreferences prefs;
    private final String[] categories = {"Ăn uống","Di chuyển","Mua sắm","Nhà cửa","Lương","Giải trí","Sức khỏe","Khác"};
    @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); setContentView(R.layout.activity_add_transaction); ThemeManager.apply(this); database=AppDatabase.getInstance(this); edtTitle=findViewById(R.id.edtTitle); edtAmount=findViewById(R.id.edtAmount); edtNote=findViewById(R.id.edtNote); spinnerCategory=findViewById(R.id.spinnerCategory); radioIncome=findViewById(R.id.radioIncome); btnSave=findViewById(R.id.btnSave); prefs=getSharedPreferences("transaction_draft", MODE_PRIVATE); spinnerCategory.setAdapter(new ArrayAdapter<>(this, android.R.layout.simple_spinner_dropdown_item, categories)); restoreDraft(); setupDraftCache(); btnSave.setOnClickListener(v -> saveTransaction()); findViewById(R.id.fabCenterAdd).setOnClickListener(v -> saveTransaction()); findViewById(R.id.navHome).setOnClickListener(v -> startActivity(new Intent(this, MainActivity.class))); findViewById(R.id.navCalendar).setOnClickListener(v -> startActivity(new Intent(this, CalendarActivity.class))); findViewById(R.id.navReport).setOnClickListener(v -> startActivity(new Intent(this, ReportActivity.class))); findViewById(R.id.navSettings).setOnClickListener(v -> startActivity(new Intent(this, SettingsActivity.class))); }
    private void saveTransaction() { String title=edtTitle.getText().toString().trim(); String amountText=edtAmount.getText().toString().trim(); if(title.isEmpty()){edtTitle.setError("Vui lòng nhập tên giao dịch"); return;} if(amountText.isEmpty()){edtAmount.setError("Vui lòng nhập số tiền"); return;} double amount; try { amount=Double.parseDouble(amountText); } catch(Exception e){ edtAmount.setError("Số tiền không hợp lệ"); return; } if(amount<=0){edtAmount.setError("Số tiền phải lớn hơn 0"); return;} String type=radioIncome.isChecked()?"INCOME":"EXPENSE"; TransactionEntity transaction = new TransactionEntity(title, amount, type, spinnerCategory.getSelectedItem().toString(), edtNote.getText().toString().trim(), System.currentTimeMillis()); long newId = database.transactionDao().insert(transaction); transaction.setId((int) newId); new FirebaseSyncManager(this).uploadTransaction(transaction); prefs.edit().clear().apply(); Toast.makeText(this,"Đã lưu giao dịch",Toast.LENGTH_SHORT).show(); finish(); }
    private void restoreDraft(){ edtTitle.setText(prefs.getString("title", "")); edtAmount.setText(prefs.getString("amount", "")); edtNote.setText(prefs.getString("note", "")); radioIncome.setChecked(prefs.getBoolean("income", true)); }
    private void setupDraftCache(){ TextWatcher w=new TextWatcher(){ public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){ saveDraft(); } public void afterTextChanged(Editable e){} }; edtTitle.addTextChangedListener(w); edtAmount.addTextChangedListener(w); edtNote.addTextChangedListener(w); radioIncome.setOnCheckedChangeListener((b,c)->saveDraft()); }
    private void saveDraft(){ prefs.edit().putString("title", edtTitle.getText().toString()).putString("amount", edtAmount.getText().toString()).putString("note", edtNote.getText().toString()).putBoolean("income", radioIncome.isChecked()).apply(); }

}
